version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "15000:8080"
      - "15001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "15002:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
      - VITE_API_URL=wss://backend:15001
